using System.IO;
using System.Text;
using WikiTools.Core;
using Xunit;

namespace WikiLib.Tests
{
    public class WikidpadWikiTests
    {
        private readonly string _testDir;
        private readonly string _dataDir;

        public WikidpadWikiTests()
        {
            _testDir = Path.Combine(TestUtilities.SetTestFolder(),"wp");
            _dataDir = Path.Combine(_testDir, "data");
        }


        [Fact]
        public void Constructor_UsesRootWhenNoDataDir()
        {
            //arrange
            if (Directory.Exists(_dataDir))
            {
                Directory.Delete(_dataDir, true);
            }
            var expected = _testDir;
            var sut = new WikidpadWiki(_testDir);
            //actual
            var actual = sut.DataDir;

            //assert
            Assert.Equal(expected, actual);

        }

        [Fact]
        public void Constructor_FindsDataDirWhenExists()
        {
            //arrange
            Directory.CreateDirectory(_dataDir);
            var expected = _dataDir;
            var sut = new WikidpadWiki(_testDir);
            //actual
            var actual = sut.DataDir;

            //assert
            Assert.Equal(expected, actual);

        }



        [Fact]
        public void Constructor_LoadsAllPages()
        {
            Directory.CreateDirectory(_dataDir);
            //arrange
            File.Create(Path.Combine(_dataDir, @"TestOne.wiki"));
            File.Create(Path.Combine(_dataDir, @"TestTwo.wiki"));
            //actual
            var sut = new WikidpadWiki(_testDir);
            var pageList = sut.GetAllPages();

            //assert
            Assert.Equal("TestOne", pageList[0].Name);
            Assert.Equal("TestTwo", pageList[1].Name);

        }
        
        [Fact]
        public void GetPageContent_GetsContentAndMarksPageAsRead()
        {
            Directory.CreateDirectory(_dataDir);
            //arrange
            var expected = "+ Test One\n\n-This wiki file is generated by tests\n[tag:tests]";
            var expected2 = "+ Test Two\n\n-This wiki file is generated by tests\n[tag:tests] CategoryTests";
            File.WriteAllText(Path.Combine(_dataDir, "TestOne.wiki"), expected);
            File.WriteAllText(Path.Combine(_dataDir, "TestTwo.wiki"), expected2);
            //actual
            var sut = new WikidpadWiki(_testDir);
            var pageList = sut.GetAllPages();

            //assert
            Assert.Equal(expected, pageList[0].GetContent());
            Assert.Equal(expected2, pageList[1].GetContent());

            Assert.True(pageList[0].ContentIsStale);            
            Assert.True(pageList[1].ContentIsStale);


        }
    }
}
